spring.application.name=backend
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=arkaprava181204@gmail.com
spring.mail.password=fkpnziwzgxbgblba

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.datasource.url=jdbc:postgresql://ep-raspy-lab-aot0mesi-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_f3yOsXFjd6hK&sslmode=require&channelBinding=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_f3yOsXFjd6hK

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

groq.api.key = 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